version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules # prevent host node_modules from overwriting container's
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      # Switch this to use the local container by default (can be overridden by .env)
      - MONGO_URI=mongodb://mongodb:27017/photoBookDB
      - REDIS_URL=redis://redis:6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: photobook-mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - photobook-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
