export const API_ROUTES = {
    AUTH: {
        LOGIN: "/auth/login",
        SIGNUP: "/auth/signup",
        REFRESH_TOKEN: "/auth/refresh-token",
        LOGOUT: "/auth/logout",
        FORGOT_PASSWORD: "/auth/forgot-password",
        RESET_PASSWORD: "/auth/reset-password",
    },
    USER: {
        PROFILE: "/user/profile",
        PROFILE_IMAGE: "/user/profile-image",
        CHANGE_PASSWORD: "/user/change-password",
        VERIFY_OTP: "/user/verify-otp",
    },
    ADMIN: {
        DASHBOARD: "/admin/dashboard",
        CATEGORIES: "/admin/categories",
        CATEGORY: "/admin/category",
        CATEGORY_DETAILS: (id: string) => `/admin/category/${id}`,
        CATEGORY_APPROVE: (id: string) => `/admin/category/${id}/approve`,
        CATEGORY_REJECT: (id: string) => `/admin/category/${id}/reject`,
        PHOTOGRAPHERS: "/admin/photographers",
        PHOTOGRAPHER_DETAILS: (id: string) => `/admin/photographers/${id}`,
        PHOTOGRAPHER_BLOCK: (id: string) => `/admin/photographers/${id}/block`,
        PHOTOGRAPHER_UNBLOCK: (id: string) => `/admin/photographers/${id}/unblock`,
        PHOTOGRAPHER_STATS: "/admin/photographers/stats",
        APPLICATIONS: "/admin/applications",
        APPLICATION_DETAILS: (id: string) => `/admin/applications/${id}`,
        APPLICATION_APPROVE: (id: string) => `/admin/applications/${id}/approve`,
        APPLICATION_REJECT: (id: string) => `/admin/applications/${id}/reject`,
        PACKAGES: "/admin/packages",
        PACKAGE_APPROVE: (id: string) => `/admin/packages/${id}/approve`,
        PACKAGE_REJECT: (id: string) => `/admin/packages/${id}/reject`,
        PACKAGE_BLOCK: (id: string) => `/admin/packages/${id}/block`,
        PACKAGE_UNBLOCK: (id: string) => `/admin/packages/${id}/unblock`,
    },
    PHOTOGRAPHER: {
        PROFILE: "/photographer/profile",
        PACKAGES: "/photographer/packages",
        PACKAGE_DETAILS: (id: string) => `/photographer/packages/${id}`,
        PORTFOLIO_SECTIONS: "/photographer/portfolio/sections",
        PORTFOLIO_SECTION: "/photographer/portfolio/section",
        PORTFOLIO_SECTION_DETAILS: (id: string) => `/photographer/portfolio/section/${id}`,
        PORTFOLIO_IMAGE: (sectionId: string) => `/photographer/portfolio/section/${sectionId}/image`,
        AVAILABILITY: "/photographer/availability",
        AVAILABILITY_BLOCK: "/photographer/availability/block-range",
        AVAILABILITY_UNBLOCK: "/photographer/availability/unblock-range",
        CATEGORY_SUGGEST: "/photographer/category/suggest",
        PUBLIC: {
            LIST: "/photographer/public/photographers",
            DETAILS: (id: string) => `/photographer/public/photographers/${id}`,
            REVIEW: (id: string) => `/photographer/public/photographers/${id}/review`,
            AVAILABILITY: (id: string) => `/photographer/public/photographers/${id}/availability`,
            PACKAGES: (photographerId: string) => `/photographer/${photographerId}/packages`,
            CATEGORIES: "/photographer/categories",
        }
    },
    BOOKING: {
        BASE: "/booking/",
        USER_ALL: "/booking/user/all",
        PHOTOGRAPHER_ALL: "/booking/photographer/all",
        DETAILS: (id: string) => `/booking/${id}`,
        ACCEPT: (id: string) => `/booking/${id}/accept`,
        REJECT: (id: string) => `/booking/${id}/reject`,
        CANCEL: (id: string) => `/booking/${id}/cancel`,
        COMPLETE: (id: string) => `/booking/${id}/complete`,
        START_WORK: (id: string) => `/booking/${id}/start-work`,
        END_WORK: (id: string) => `/booking/${id}/end-work`,
        DELIVER_WORK: (id: string) => `/booking/${id}/deliver-work`,
        CONFIRM_END_WORK: (id: string) => `/booking/${id}/confirm-end-work`,
        CONFIRM_DELIVERY: (id: string) => `/booking/${id}/confirm-delivery`,
        PAYMENT_INTENT: (id: string) => `/booking/${id}/payment-intent`,
        PAY: (id: string) => `/booking/${id}/pay`,
        RESCHEDULE_REQUEST: (id: string) => `/booking/${id}/reschedule-request`,
        RESCHEDULE_RESPONSE: (id: string) => `/booking/${id}/reschedule-response`,
    },
    RENTAL: {
        ITEMS: "/rental/items",
        MY_ITEMS: "/rental/my-items",
        ITEM_DETAILS: (id: string) => `/rental/items/${id}`,
        ITEM_STATUS: (id: string) => `/rental/items/${id}/status`,
        ITEM_AVAILABILITY: (id: string) => `/rental/items/${id}/availability`,
        ITEM_UNAVAILABLE: (id: string) => `/rental/items/${id}/unavailable`,
        ITEM_BLOCK: (id: string) => `/rental/items/${id}/block`,
        ITEM_UNBLOCK: (id: string) => `/rental/items/${id}/unblock`,
        UPDATE: (id: string) => `/rental/items/${id}`,
        ORDERS: "/rental/orders",
        ORDER_DETAILS: (id: string) => `/rental/orders/${id}`,
        OWNER_ORDERS: "/rental/owner/orders",
        ADMIN_ITEMS: "/rental/admin/items",
        ADMIN_ORDERS: "/rental/admin/orders",
        ADMIN_ORDER_DETAILS: (id: string) => `/rental/admin/orders/${id}`,
        STATS: "/rental/stats",
        ACCEPT: (id: string) => `/rental/orders/${id}/accept`,
        REJECT: (id: string) => `/rental/orders/${id}/reject`,
        CANCEL: (id: string) => `/rental/orders/${id}/cancel`,
        COMPLETE: (id: string) => `/rental/orders/${id}/complete`,
        PAY: (id: string) => `/rental/orders/${id}/pay`,
        PAY_BALANCE: (id: string) => `/rental/orders/${id}/pay-balance`,
        PAYMENT_INTENT: (id: string) => `/rental/orders/${id}/payment-intent`,
        BALANCE_PAYMENT_INTENT: (id: string) => `/rental/orders/${id}/balance-payment-intent`,
        CONFIRM_PAYMENT: (id: string) => `/rental/orders/${id}/confirm-payment`,
        RESCHEDULE: (id: string) => `/rental/${id}/reschedule`,
        RESCHEDULE_RESPOND: (id: string) => `/rental/${id}/reschedule/respond`,
        UPDATE_ORDER_STATUS: (id: string) => `/rental/orders/${id}/status`,
    },
    MESSAGE: {
        BASE: "/message",
        SENT: "/message/sent",
        READ: (id: string) => `/message/${id}/read`,
        DELETE: (id: string) => `/message/${id}`,
    },
    WALLET: {
        DETAILS: "/wallet",
        DASHBOARD_STATS: "/wallet/dashboard-stats",
        ESCROW_STATS: "/wallet/escrow-stats",
        TRANSACTIONS: "/wallet/transactions",
    },
    REPORT: {
        BASE: "/report",
        STATUS: (id: string) => `/report/${id}/status`,
        FORWARD_CHAT: (id: string) => `/report/${id}/forward-chat`,
        APPLY_PENALTY: (id: string) => `/report/${id}/penalty`,
        EVIDENCE_UPLOAD: "/api/v1/reports/evidence/upload",
    },
    REPORT_CATEGORY: {
        BASE: "/report-categories",
        PUBLIC: "/report-categories/public",
        DETAILS: (id: string) => `/report-categories/${id}`,
    },
    REVIEW: {
        BASE: "/reviews",
        DETAILS: (id: string) => `/reviews/${id}`,
        STATS: (id: string) => `/reviews/stats/${id}`,
        REPLY: (id: string) => `/reviews/${id}/reply`,
        LIKE: (id: string) => `/reviews/${id}/like`,
        MY_REVIEWS: "/reviews/user/my-reviews",
        RECEIVED_REVIEWS: "/reviews/user/received-reviews",
    },
    HELP: {
        BASE: "/help",
        CATEGORY: (category: string) => `/help/category/${category}`,
        DETAILS: (id: string) => `/help/${id}`,
        REORDER: (id: string) => `/help/reorder/${id}`,
    },
    HELP_REQUEST: {
        BASE: "/help-requests",
        STATUS: (id: string) => `/help-requests/${id}/status`,
    },
    RULES: {
        BASE: "/rules",
    },
    PAYMENT: {
        CREATE_INTENT: "/payment/create-intent",
        CONFIRM: "/payment/confirm",
    },
    LIKE: {
        PHOTOGRAPHER: (id: string) => `/photographer/public/photographers/${id}/like`,
        PACKAGE: (id: string) => `/photographer/packages/${id}/like`,
        PORTFOLIO: (id: string) => `/photographer/portfolio/section/${id}/like`,
        RENTAL: (id: string) => `/rental/items/${id}/like`,
    }
} as const;
