/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Photographer_layoutRouteImport } from './routes/photographer/__layout'
import { Route as Main_layoutRouteImport } from './routes/main/__layout'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/resetPassword'
import { Route as AuthResetOtpRouteImport } from './routes/auth/reset-otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forgetPassword'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as Photographer_layoutProfileRouteImport } from './routes/photographer/__layout/profile'
import { Route as Photographer_layoutDashboardRouteImport } from './routes/photographer/__layout/dashboard'
import { Route as Photographer_layoutApplyRouteImport } from './routes/photographer/__layout/apply'
import { Route as Main_layoutProfileRouteImport } from './routes/main/__layout/profile'
import { Route as Main_layoutHomeRouteImport } from './routes/main/__layout/home'
import { Route as Main_layoutEditProfileRouteImport } from './routes/main/__layout/editProfile'
import { Route as AdminPhotographersIdRouteImport } from './routes/admin/photographers.$id'
import { Route as Admin_layoutUsermanagementRouteImport } from './routes/admin/__layout/usermanagement'
import { Route as Admin_layoutPhotographersRouteImport } from './routes/admin/__layout/photographers'
import { Route as Admin_layoutDashboardRouteImport } from './routes/admin/__layout/dashboard'
import { Route as Admin_layoutApplicationsIndexRouteImport } from './routes/admin/__layout/applications/index'
import { Route as Admin_layoutApplicationsIdRouteImport } from './routes/admin/__layout/applications/$id'

const PhotographerRouteImport = createFileRoute('/photographer')()
const MainRouteImport = createFileRoute('/main')()
const AuthRouteImport = createFileRoute('/auth')()
const AdminRouteImport = createFileRoute('/admin')()

const PhotographerRoute = PhotographerRouteImport.update({
  id: '/photographer',
  path: '/photographer',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Photographer_layoutRoute = Photographer_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => PhotographerRoute,
} as any)
const Main_layoutRoute = Main_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetOtpRoute = AuthResetOtpRouteImport.update({
  id: '/reset-otp',
  path: '/reset-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthRoute,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)
const Photographer_layoutProfileRoute =
  Photographer_layoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Photographer_layoutRoute,
  } as any)
const Photographer_layoutDashboardRoute =
  Photographer_layoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Photographer_layoutRoute,
  } as any)
const Photographer_layoutApplyRoute =
  Photographer_layoutApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => Photographer_layoutRoute,
  } as any)
const Main_layoutProfileRoute = Main_layoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutHomeRoute = Main_layoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutEditProfileRoute = Main_layoutEditProfileRouteImport.update({
  id: '/editProfile',
  path: '/editProfile',
  getParentRoute: () => Main_layoutRoute,
} as any)
const AdminPhotographersIdRoute = AdminPhotographersIdRouteImport.update({
  id: '/photographers/$id',
  path: '/photographers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Admin_layoutUsermanagementRoute =
  Admin_layoutUsermanagementRouteImport.update({
    id: '/usermanagement',
    path: '/usermanagement',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutPhotographersRoute =
  Admin_layoutPhotographersRouteImport.update({
    id: '/photographers',
    path: '/photographers',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutDashboardRoute = Admin_layoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Admin_layoutRoute,
} as any)
const Admin_layoutApplicationsIndexRoute =
  Admin_layoutApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutApplicationsIdRoute =
  Admin_layoutApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => Admin_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/admin': typeof Admin_layoutRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof Main_layoutRouteWithChildren
  '/photographer': typeof Photographer_layoutRouteWithChildren
  '/admin/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/photographers': typeof Admin_layoutPhotographersRoute
  '/admin/usermanagement': typeof Admin_layoutUsermanagementRoute
  '/admin/photographers/$id': typeof AdminPhotographersIdRoute
  '/main/editProfile': typeof Main_layoutEditProfileRoute
  '/main/home': typeof Main_layoutHomeRoute
  '/main/profile': typeof Main_layoutProfileRoute
  '/photographer/apply': typeof Photographer_layoutApplyRoute
  '/photographer/dashboard': typeof Photographer_layoutDashboardRoute
  '/photographer/profile': typeof Photographer_layoutProfileRoute
  '/admin/applications/$id': typeof Admin_layoutApplicationsIdRoute
  '/admin/applications': typeof Admin_layoutApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/admin': typeof Admin_layoutRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof Main_layoutRouteWithChildren
  '/photographer': typeof Photographer_layoutRouteWithChildren
  '/admin/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/photographers': typeof Admin_layoutPhotographersRoute
  '/admin/usermanagement': typeof Admin_layoutUsermanagementRoute
  '/admin/photographers/$id': typeof AdminPhotographersIdRoute
  '/main/editProfile': typeof Main_layoutEditProfileRoute
  '/main/home': typeof Main_layoutHomeRoute
  '/main/profile': typeof Main_layoutProfileRoute
  '/photographer/apply': typeof Photographer_layoutApplyRoute
  '/photographer/dashboard': typeof Photographer_layoutDashboardRoute
  '/photographer/profile': typeof Photographer_layoutProfileRoute
  '/admin/applications/$id': typeof Admin_layoutApplicationsIdRoute
  '/admin/applications': typeof Admin_layoutApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/__layout': typeof Admin_layoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof MainRouteWithChildren
  '/main/__layout': typeof Main_layoutRouteWithChildren
  '/photographer': typeof PhotographerRouteWithChildren
  '/photographer/__layout': typeof Photographer_layoutRouteWithChildren
  '/admin/__layout/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/__layout/photographers': typeof Admin_layoutPhotographersRoute
  '/admin/__layout/usermanagement': typeof Admin_layoutUsermanagementRoute
  '/admin/photographers/$id': typeof AdminPhotographersIdRoute
  '/main/__layout/editProfile': typeof Main_layoutEditProfileRoute
  '/main/__layout/home': typeof Main_layoutHomeRoute
  '/main/__layout/profile': typeof Main_layoutProfileRoute
  '/photographer/__layout/apply': typeof Photographer_layoutApplyRoute
  '/photographer/__layout/dashboard': typeof Photographer_layoutDashboardRoute
  '/photographer/__layout/profile': typeof Photographer_layoutProfileRoute
  '/admin/__layout/applications/$id': typeof Admin_layoutApplicationsIdRoute
  '/admin/__layout/applications/': typeof Admin_layoutApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/admin'
    | '/auth'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/photographer'
    | '/admin/dashboard'
    | '/admin/photographers'
    | '/admin/usermanagement'
    | '/admin/photographers/$id'
    | '/main/editProfile'
    | '/main/home'
    | '/main/profile'
    | '/photographer/apply'
    | '/photographer/dashboard'
    | '/photographer/profile'
    | '/admin/applications/$id'
    | '/admin/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/admin'
    | '/auth'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/photographer'
    | '/admin/dashboard'
    | '/admin/photographers'
    | '/admin/usermanagement'
    | '/admin/photographers/$id'
    | '/main/editProfile'
    | '/main/home'
    | '/main/profile'
    | '/photographer/apply'
    | '/photographer/dashboard'
    | '/photographer/profile'
    | '/admin/applications/$id'
    | '/admin/applications'
  id:
    | '__root__'
    | '/about'
    | '/admin'
    | '/admin/__layout'
    | '/auth'
    | '/auth/__layout'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/main/__layout'
    | '/photographer'
    | '/photographer/__layout'
    | '/admin/__layout/dashboard'
    | '/admin/__layout/photographers'
    | '/admin/__layout/usermanagement'
    | '/admin/photographers/$id'
    | '/main/__layout/editProfile'
    | '/main/__layout/home'
    | '/main/__layout/profile'
    | '/photographer/__layout/apply'
    | '/photographer/__layout/dashboard'
    | '/photographer/__layout/profile'
    | '/admin/__layout/applications/$id'
    | '/admin/__layout/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  PhotographerRoute: typeof PhotographerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photographer': {
      id: '/photographer'
      path: '/photographer'
      fullPath: '/photographer'
      preLoaderRoute: typeof PhotographerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographer/__layout': {
      id: '/photographer/__layout'
      path: '/photographer'
      fullPath: '/photographer'
      preLoaderRoute: typeof Photographer_layoutRouteImport
      parentRoute: typeof PhotographerRoute
    }
    '/main/__layout': {
      id: '/main/__layout'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof Main_layoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/resetPassword': {
      id: '/auth/resetPassword'
      path: '/resetPassword'
      fullPath: '/auth/resetPassword'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-otp': {
      id: '/auth/reset-otp'
      path: '/reset-otp'
      fullPath: '/auth/reset-otp'
      preLoaderRoute: typeof AuthResetOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgetPassword': {
      id: '/auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/auth/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/photographer/__layout/profile': {
      id: '/photographer/__layout/profile'
      path: '/profile'
      fullPath: '/photographer/profile'
      preLoaderRoute: typeof Photographer_layoutProfileRouteImport
      parentRoute: typeof Photographer_layoutRoute
    }
    '/photographer/__layout/dashboard': {
      id: '/photographer/__layout/dashboard'
      path: '/dashboard'
      fullPath: '/photographer/dashboard'
      preLoaderRoute: typeof Photographer_layoutDashboardRouteImport
      parentRoute: typeof Photographer_layoutRoute
    }
    '/photographer/__layout/apply': {
      id: '/photographer/__layout/apply'
      path: '/apply'
      fullPath: '/photographer/apply'
      preLoaderRoute: typeof Photographer_layoutApplyRouteImport
      parentRoute: typeof Photographer_layoutRoute
    }
    '/main/__layout/profile': {
      id: '/main/__layout/profile'
      path: '/profile'
      fullPath: '/main/profile'
      preLoaderRoute: typeof Main_layoutProfileRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/main/__layout/home': {
      id: '/main/__layout/home'
      path: '/home'
      fullPath: '/main/home'
      preLoaderRoute: typeof Main_layoutHomeRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/main/__layout/editProfile': {
      id: '/main/__layout/editProfile'
      path: '/editProfile'
      fullPath: '/main/editProfile'
      preLoaderRoute: typeof Main_layoutEditProfileRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/admin/photographers/$id': {
      id: '/admin/photographers/$id'
      path: '/photographers/$id'
      fullPath: '/admin/photographers/$id'
      preLoaderRoute: typeof AdminPhotographersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/__layout/usermanagement': {
      id: '/admin/__layout/usermanagement'
      path: '/usermanagement'
      fullPath: '/admin/usermanagement'
      preLoaderRoute: typeof Admin_layoutUsermanagementRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/admin/__layout/photographers': {
      id: '/admin/__layout/photographers'
      path: '/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof Admin_layoutPhotographersRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/admin/__layout/dashboard': {
      id: '/admin/__layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof Admin_layoutDashboardRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/admin/__layout/applications/': {
      id: '/admin/__layout/applications/'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof Admin_layoutApplicationsIndexRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/admin/__layout/applications/$id': {
      id: '/admin/__layout/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof Admin_layoutApplicationsIdRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
  }
}

interface Admin_layoutRouteChildren {
  Admin_layoutDashboardRoute: typeof Admin_layoutDashboardRoute
  Admin_layoutPhotographersRoute: typeof Admin_layoutPhotographersRoute
  Admin_layoutUsermanagementRoute: typeof Admin_layoutUsermanagementRoute
  Admin_layoutApplicationsIdRoute: typeof Admin_layoutApplicationsIdRoute
  Admin_layoutApplicationsIndexRoute: typeof Admin_layoutApplicationsIndexRoute
}

const Admin_layoutRouteChildren: Admin_layoutRouteChildren = {
  Admin_layoutDashboardRoute: Admin_layoutDashboardRoute,
  Admin_layoutPhotographersRoute: Admin_layoutPhotographersRoute,
  Admin_layoutUsermanagementRoute: Admin_layoutUsermanagementRoute,
  Admin_layoutApplicationsIdRoute: Admin_layoutApplicationsIdRoute,
  Admin_layoutApplicationsIndexRoute: Admin_layoutApplicationsIndexRoute,
}

const Admin_layoutRouteWithChildren = Admin_layoutRoute._addFileChildren(
  Admin_layoutRouteChildren,
)

interface AdminRouteChildren {
  Admin_layoutRoute: typeof Admin_layoutRouteWithChildren
  AdminPhotographersIdRoute: typeof AdminPhotographersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  Admin_layoutRoute: Admin_layoutRouteWithChildren,
  AdminPhotographersIdRoute: AdminPhotographersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetOtpRoute: typeof AuthResetOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth_layoutRoute: Auth_layoutRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetOtpRoute: AuthResetOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface Main_layoutRouteChildren {
  Main_layoutEditProfileRoute: typeof Main_layoutEditProfileRoute
  Main_layoutHomeRoute: typeof Main_layoutHomeRoute
  Main_layoutProfileRoute: typeof Main_layoutProfileRoute
}

const Main_layoutRouteChildren: Main_layoutRouteChildren = {
  Main_layoutEditProfileRoute: Main_layoutEditProfileRoute,
  Main_layoutHomeRoute: Main_layoutHomeRoute,
  Main_layoutProfileRoute: Main_layoutProfileRoute,
}

const Main_layoutRouteWithChildren = Main_layoutRoute._addFileChildren(
  Main_layoutRouteChildren,
)

interface MainRouteChildren {
  Main_layoutRoute: typeof Main_layoutRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  Main_layoutRoute: Main_layoutRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface Photographer_layoutRouteChildren {
  Photographer_layoutApplyRoute: typeof Photographer_layoutApplyRoute
  Photographer_layoutDashboardRoute: typeof Photographer_layoutDashboardRoute
  Photographer_layoutProfileRoute: typeof Photographer_layoutProfileRoute
}

const Photographer_layoutRouteChildren: Photographer_layoutRouteChildren = {
  Photographer_layoutApplyRoute: Photographer_layoutApplyRoute,
  Photographer_layoutDashboardRoute: Photographer_layoutDashboardRoute,
  Photographer_layoutProfileRoute: Photographer_layoutProfileRoute,
}

const Photographer_layoutRouteWithChildren =
  Photographer_layoutRoute._addFileChildren(Photographer_layoutRouteChildren)

interface PhotographerRouteChildren {
  Photographer_layoutRoute: typeof Photographer_layoutRouteWithChildren
}

const PhotographerRouteChildren: PhotographerRouteChildren = {
  Photographer_layoutRoute: Photographer_layoutRouteWithChildren,
}

const PhotographerRouteWithChildren = PhotographerRoute._addFileChildren(
  PhotographerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  PhotographerRoute: PhotographerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
