/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MainHomeRouteImport } from './routes/main/home'
import { Route as Main_layoutRouteImport } from './routes/main/__layout'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/resetPassword'
import { Route as AuthResetOtpRouteImport } from './routes/auth/reset-otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forgetPassword'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as Admin_layoutUsermanagementRouteImport } from './routes/admin/__layout/usermanagement'
import { Route as Admin_layoutDashboardRouteImport } from './routes/admin/__layout/dashboard'

const MainRouteImport = createFileRoute('/main')()
const AuthRouteImport = createFileRoute('/auth')()
const AdminRouteImport = createFileRoute('/admin')()

const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const Main_layoutRoute = Main_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetOtpRoute = AuthResetOtpRouteImport.update({
  id: '/reset-otp',
  path: '/reset-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthRoute,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)
const Admin_layoutUsermanagementRoute =
  Admin_layoutUsermanagementRouteImport.update({
    id: '/usermanagement',
    path: '/usermanagement',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutDashboardRoute = Admin_layoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Admin_layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/admin': typeof Admin_layoutRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof Main_layoutRoute
  '/main/home': typeof MainHomeRoute
  '/admin/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/usermanagement': typeof Admin_layoutUsermanagementRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/admin': typeof Admin_layoutRouteWithChildren
  '/auth': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof Main_layoutRoute
  '/main/home': typeof MainHomeRoute
  '/admin/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/usermanagement': typeof Admin_layoutUsermanagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/__layout': typeof Admin_layoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-otp': typeof AuthResetOtpRoute
  '/auth/resetPassword': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/main': typeof MainRouteWithChildren
  '/main/__layout': typeof Main_layoutRoute
  '/main/home': typeof MainHomeRoute
  '/admin/__layout/dashboard': typeof Admin_layoutDashboardRoute
  '/admin/__layout/usermanagement': typeof Admin_layoutUsermanagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/admin'
    | '/auth'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/main/home'
    | '/admin/dashboard'
    | '/admin/usermanagement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/admin'
    | '/auth'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/main/home'
    | '/admin/dashboard'
    | '/admin/usermanagement'
  id:
    | '__root__'
    | '/about'
    | '/admin'
    | '/admin/__layout'
    | '/auth'
    | '/auth/__layout'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/reset-otp'
    | '/auth/resetPassword'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/main'
    | '/main/__layout'
    | '/main/home'
    | '/admin/__layout/dashboard'
    | '/admin/__layout/usermanagement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/home': {
      id: '/main/home'
      path: '/home'
      fullPath: '/main/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/__layout': {
      id: '/main/__layout'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof Main_layoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/resetPassword': {
      id: '/auth/resetPassword'
      path: '/resetPassword'
      fullPath: '/auth/resetPassword'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-otp': {
      id: '/auth/reset-otp'
      path: '/reset-otp'
      fullPath: '/auth/reset-otp'
      preLoaderRoute: typeof AuthResetOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgetPassword': {
      id: '/auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/auth/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/__layout/usermanagement': {
      id: '/admin/__layout/usermanagement'
      path: '/usermanagement'
      fullPath: '/admin/usermanagement'
      preLoaderRoute: typeof Admin_layoutUsermanagementRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/admin/__layout/dashboard': {
      id: '/admin/__layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof Admin_layoutDashboardRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
  }
}

interface Admin_layoutRouteChildren {
  Admin_layoutDashboardRoute: typeof Admin_layoutDashboardRoute
  Admin_layoutUsermanagementRoute: typeof Admin_layoutUsermanagementRoute
}

const Admin_layoutRouteChildren: Admin_layoutRouteChildren = {
  Admin_layoutDashboardRoute: Admin_layoutDashboardRoute,
  Admin_layoutUsermanagementRoute: Admin_layoutUsermanagementRoute,
}

const Admin_layoutRouteWithChildren = Admin_layoutRoute._addFileChildren(
  Admin_layoutRouteChildren,
)

interface AdminRouteChildren {
  Admin_layoutRoute: typeof Admin_layoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  Admin_layoutRoute: Admin_layoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetOtpRoute: typeof AuthResetOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth_layoutRoute: Auth_layoutRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetOtpRoute: AuthResetOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  Main_layoutRoute: typeof Main_layoutRoute
  MainHomeRoute: typeof MainHomeRoute
}

const MainRouteChildren: MainRouteChildren = {
  Main_layoutRoute: Main_layoutRoute,
  MainHomeRoute: MainHomeRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
