export const ROUTES = {
  V1: {
    AUTH: {
      BASE: "/api/v1/auth",
      SIGNUP: "/signup",
      VERIFY_OTP: "/verify-otp",
      RESEND_OTP: "/resend-otp",
      LOGIN: "/login",
      GOOGLE_LOGIN: "/google-login",
      REFRESH: "/refresh-token",
      LOGOUT: "/logout",
      FORGOT_PASSWORD: "/forgot-password",
      VERIFY_RESET_OTP: "/verify-reset-otp",
      RESET_PASSWORD: "/reset-password",
    },
    USER: {
      BASE: "/api/v1/user",
      PROFILE: "/profile",
      UPDATE_PROFILE: "/update-profile",
      CHANGE_PASSWORD: "/change-password",
      INITIATE_CHANGE_PASSWORD: "/initiate-change-password",
      PROFILE_IMAGE: "/profile-image",
      VERIFY_OTP: "/verify-otp",
    },
    PHOTOGRAPHER: {
      BASE: "/api/v1/photographer",
      APPLY: "/apply",
      DASHBOARD: "/dashboard",
      SUGGEST_CATEGORY: "/category/suggest",
      GET_BOOKINGS: "/bookings",

      PORTFOLIO_SECTION: "/portfolio/section",
      PORTFOLIO_SECTIONS: "/portfolio/sections",
      PORTFOLIO_SECTION_BY_ID: "/portfolio/section/:id",
      PORTFOLIO_SECTION_TOGGLE_LIKE: "/portfolio/section/:id/like",
      PORTFOLIO_SECTION_IMAGE: "/portfolio/section/:id/image",

      PACKAGES: "/packages",
      PACKAGE_BY_ID: "/packages/:id",
      PACKAGE_TOGGLE_LIKE: "/packages/:id/like",
      PUBLIC_PACKAGES: "/:photographerId/packages",

      AVAILABILITY: "/availability",
      BLOCK_RANGE: "/availability/block-range",
      UNBLOCK_RANGE: "/availability/unblock-range",
      DELETE_AVAILABILITY: "/availability/:date",

      PUBLIC_AVAILABILITY: "/public/photographers/:id/availability",
      PUBLIC_LIST: "/public/photographers",
      PUBLIC_DETAILS: "/public/photographers/:id",
      TOGGLE_LIKE: "/public/photographers/:id/like",
      ADD_REVIEW: "/public/photographers/:id/review",

      CATEGORIES: "/categories",
    },
    ADMIN: {
      BASE: "/api/v1/admin",

      USERS: "/users",
      USER_BY_ID: "/users/:id",
      BLOCK: "/users/:id/block",
      UNBLOCK: "/users/:id/unblock",

      PHOTOGRAPHERS: "/photographers",
      PHOTOGRAPHER_STATS: "/photographers/stats",
      PHOTOGRAPHER_BY_ID: "/photographers/:id",
      PHOTOGRAPHER_BLOCK: "/photographers/:id/block",
      PHOTOGRAPHER_UNBLOCK: "/photographers/:id/unblock",

      APPLICATIONS: "/applications",
      APPLICATION_BY_ID: "/applications/:id",
      APPLICATION_APPROVE: "/applications/:id/approve",
      APPLICATION_REJECT: "/applications/:id/reject",

      PACKAGES: "/packages",
      PACKAGE_APPROVE: "/packages/:id/approve",
      PACKAGE_REJECT: "/packages/:id/reject",
      PACKAGE_BLOCK: "/packages/:id/block",
      PACKAGE_UNBLOCK: "/packages/:id/unblock",

      CATEGORY: "/category",
      CATEGORY_BY_ID: "/category/:id",
      CATEGORY_APPROVE: "/category/:id/approve",
      CATEGORY_REJECT: "/category/:id/reject",
      CATEGORIES: "/categories",
    },
    BOOKING: {
      BASE: "/api/v1/booking",
      CREATE: "/",
      DETAILS: "/:id",
      USER_BOOKINGS: "/user/all",
      PHOTOGRAPHER_BOOKINGS: "/photographer/all",
      ACCEPT: "/:id/accept",
      REJECT: "/:id/reject",
      CANCEL: "/:id/cancel",
      PAY: "/:id/pay",
      PAYMENT_INTENT: "/:id/payment-intent",
      START_WORK: "/:id/start-work",
      END_WORK: "/:id/end-work",
      CONFIRM_END_WORK: "/:id/confirm-end-work",
      DELIVER_WORK: "/:id/deliver-work",
      CONFIRM_DELIVERY: "/:id/confirm-delivery",
      COMPLETE: "/:id/complete",
      RESCHEDULE_REQUEST: "/:id/reschedule-request",
      RESCHEDULE_RESPONSE: "/:id/reschedule-response",
    },
    MESSAGE: {
      BASE: "/api/v1/message",
      GET_ALL: "/",
      GET_SENT: "/sent",
      MARK_READ: "/:id/read",
      DELETE: "/:id",
      SEND: "/",
    },
    PAYMENT: {
      BASE: "/api/v1/payment",
      CREATE_INTENT: "/create-intent",
      CONFIRM: "/confirm",
    },
    WALLET: {
      BASE: "/api/v1/wallet",
      DETAILS: "/",
      TRANSACTIONS: "/transactions",
      ESCROW_STATS: "/escrow-stats",
      DASHBOARD_STATS: "/dashboard-stats",
    },
    RENTAL: {
      BASE: "/api/v1/rental",
      GET_ITEMS: "/items",
      GET_ITEM_DETAILS: "/items/:id",
      RENT_ITEM: "/orders",
      USER_ORDERS: "/orders",
      CONFIRM_PAYMENT: "/orders/:id/confirm-payment",
      MY_ITEMS: "/my-items",
      UPDATE_ITEM_STATUS: "/items/:id/status",
      ADMIN_ITEMS: "/admin/items",
      OWNER_ORDERS: "/owner/orders",
      ADMIN_ORDERS: "/admin/orders",
      UPDATE_ORDER_STATUS: "/orders/:id/status",
      ADMIN_ORDER_DETAILS: "/admin/orders/:id",
      ACCEPT_ORDER: "/orders/:id/accept",
      REJECT_ORDER: "/orders/:id/reject",
      PAY_DEPOSIT: "/orders/:id/pay",
      DEPOSIT_INTENT: "/orders/:id/payment-intent",
      BALANCE_INTENT: "/orders/:id/balance-payment-intent",
      PAY_BALANCE: "/orders/:id/pay-balance",
      COMPLETE_ORDER: "/orders/:id/complete",
      UPDATE_ITEM: "/items/:id",
      CHECK_AVAILABILITY: "/items/:id/availability",
      GET_UNAVAILABLE: "/items/:id/unavailable",
      BLOCK_ITEM: "/items/:id/block",
      UNBLOCK_ITEM: "/items/:id/unblock",
      TOGGLE_LIKE: "/items/:id/like",
      CANCEL_ORDER: "/orders/:id/cancel",
      STATS: "/stats",
    },
    REVIEWS: {
      BASE: "/api/v1/reviews",
    },
    REPORT: {
      BASE: "/api/v1/report",
      CREATE: "/",
      GET_ALL: "/",
      UPDATE_STATUS: "/:id/status",
    },
  },
} as const;
